import type { Metadata } from "next";
import { FiArrowUpRight, FiBriefcase, FiDownload, FiMail } from "react-icons/fi";
import { audienceSnapshot, mediaKitUrl, partnershipAudienceProof } from "../audience";
import PageHero from "../components/PageHero";
import SiteFooter from "../components/SiteFooter";
import SiteHeader from "../components/SiteHeader";

export const metadata: Metadata = { title: "Work With Me", description: "Partner with SenpaiS1lva on anime, entertainment, gaming, and culture-forward campaigns." };
const partnershipEmail = "animejay89@gmail.com";
const services = ["Sponsored short-form videos", "Streaming and entertainment campaigns", "Product integrations", "Event and convention coverage", "Creator collaborations", "Long-term ambassadorships"];

export default function WorkWithMePage() {
  return <main id="main-content" className="inner-page work-page"><SiteHeader /><PageHero eyebrow="For brands & collaborators" title={<>Make something people <em>want to watch.</em></>} intro="Authentic creator partnerships built around anime, donghua, entertainment, culture, and an audience that can smell a forced advertisement from three arcs away." action={<a className="primary-button" href={`mailto:${partnershipEmail}?subject=Partnership%20Inquiry%20for%20SenpaiS1lva`}><FiMail /> Start a conversation</a>} />
    <section className="container page-section"><div className="brand-fit-grid"><article><FiBriefcase /><p className="eyebrow">Best fit</p><h2>Respect the audience. Keep the creator voice.</h2><p>SenpaiS1lva works best with brands that want a natural place inside the conversation, not a commercial awkwardly taped to the front of it.</p><p>SenpaiS1lva is also building a bridge for anime fans discovering donghua, especially 2D and story-forward Chinese animation.</p></article><div className="service-list">{services.map((service, index) => <div key={service}><span>0{index + 1}</span><strong>{service}</strong></div>)}</div></div></section>
    <section className="container work-audience-section"><div className="work-audience-heading"><p className="eyebrow">Verified reach</p><h2>A niche audience with real creator trust.</h2><p>SenpaiS1lva reaches anime and donghua fans across short-form, social, and community platforms, with content built around recommendations, reactions, culture, and deeper conversation.</p><div className="audience-meta"><span>{audienceSnapshot.verifiedLabel}</span><span>{audienceSnapshot.lastUpdated}</span></div></div><div className="audience-grid audience-grid--compact" aria-label="Verified SenpaiS1lva audience numbers"><article className="audience-card audience-card--total" aria-label={audienceSnapshot.total.ariaLabel}><span>{audienceSnapshot.total.label}</span><strong>{audienceSnapshot.total.value}</strong><small>verified followers</small></article><div className="audience-platform-grid" aria-label="Verified platform follower breakdown">{audienceSnapshot.platforms.map((metric) => <article className="audience-card audience-card--platform" key={metric.label} aria-label={metric.ariaLabel}><strong>{metric.value}</strong><span>{metric.label}</span></article>)}</div></div><div className="partnership-proof-grid">{partnershipAudienceProof.map((item) => <article key={item.label}><span>{item.label}</span><p>{item.value}</p></article>)}</div></section>
    <section className="container process-section"><div className="page-section-heading"><div><p className="eyebrow">How it works</p><h2>Clear from pitch to post.</h2></div></div><div className="process-grid"><article><span>01</span><h3>Fit</h3><p>We confirm the campaign genuinely belongs in the SenpaiS1lva universe.</p></article><article><span>02</span><h3>Concept</h3><p>The brand goal becomes a creator-led idea the audience will actually care about.</p></article><article><span>03</span><h3>Delivery</h3><p>Clear expectations, platform-ready creative, and direct communication throughout.</p></article></div></section>
    <section className="contact-panel"><div className="container contact-panel-inner"><div><p className="eyebrow">Partnership inquiries</p><h2>Let’s build the right thing.</h2><p className="contact-panel-note">Use the inquiry button for collaboration requests, campaign fit, or media kit follow-up.</p></div><div className="contact-actions"><a className="primary-button" href={`mailto:${partnershipEmail}?subject=Partnership%20Inquiry%20for%20SenpaiS1lva`}><FiMail /> Partnership inquiry</a><a className="editorial-link" href={mediaKitUrl} target="_blank" rel="noopener noreferrer"><FiDownload /> View media kit <FiArrowUpRight /></a></div></div></section><SiteFooter /></main>;
}